apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-cat
spec:
  selector:
    matchLabels:
      app: pets
      ver: cat
  replicas: 1
  template:
    metadata:
      labels:
        app: pets
        ver: cat
    spec:
      containers:
      - name: app
        image: lukaszkaluzny/k8s-canary-on-ingress:cat
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: pets-cat
spec:
  selector:
    app: pets
    ver: cat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080